# -*- coding: utf-8 -*-
"""digit-recorgination-using-random-forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbCOIcIDJ41BHSS5HyeETSSGm47BFu3B
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/kaggle/input/digit-recorgination/digit.csv")

df.head()

df.tail()

df.isna().sum()

"""We are not doing Exploritory Data Analysis As the data is that of image"""

X=df.iloc[:,1:]

X.shape

y=df.iloc[:,0]

y.shape

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state= 0)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

"""Now we will calculate the model Accuracy"""

from sklearn.metrics import accuracy_score
print("The Accuracy score of the model: {0}".format(accuracy_score(y_test,y_pred)*100))

index=10
print("Predicted " + str(model.predict(X_test)[index]))
plt.axis('off')
plt.imshow(X_test.iloc[index].values.reshape((28,28)),cmap='gray')